### ISSUE TITLE
Bug: Cli执行报错，跑通后也没有输出模板产物

### ISSUE THREAD

**Issue by Albert-cord** [dolliejs/dollie#25]
## What is your environment?

- Dollie.js package version 
3.0.1
- Content of `dollie.json` or `dollie.js` in your template 
没有配置；
没看懂这个json配置的意义，需要handler？
跟了下代码发现命令是根据github的API, 运行：
dollie init dolliejs/template-react tr 
或者 dollie init dolliejs/scaffold-vite-react v-r
跟着命令行问答了下，可是 tr v-r文件夹下没有输出。。。
- Operating system version
Windows 10 专业版 20H2 内部版本号：19042.1165 
- Node version
v14.15.0
## What is the current behavior?
所以这个项目的输出是什么？看了https://dollie.lenconda.top/ 有点感兴趣，折腾了下代码执行、命令行执行，都没跑通
## What is the expected behavior?
麻烦开源的话MD至少给个能跑通的示例，可以的话可以搞个实例仓库

**Comment by lenconda** [comment]
1. Dollie needs an Origin Handler to get the template package from remote, but there is two built-in remote Origin Handlers in Dollie Core: `github` and `gitlab`, if you do not specify the Origin Handler ID, just like `dolliejs/template-react` which you have passed to Dollie CLI, Dollie Core will automatically use `github` to handle it
2. `dollie.json` or `dollie.js` is a configuration file for templates, this file will only be read by Dollie when generating project code and will not exist in the generated project directory
3. You had the right syntax for dollie version 3.x, and I have tried your two commands, Dollie generated project code correctly into those two dirs you mentioned above

<hr />

1. Dollie 需要一个 Origin Handler 从远程拉取模板包，但是 Dollie 内置了两个 Origin Handler：`github` 和 `gitlab`，如果你不指定 Origin Handler 的 ID，就像你传递给 Dollie CLI 的 `dolliejs/template-react` 一样，Dollie Core 将会自动使用 `github` 处理它
2. `dollie.json` 或 `dollie.js` 都是模板中的配置文件，这个文件只会在生成项目代码时被 Dollie 读取，并且不会出现在已生成的项目目录中
3. 你使用 dollie 3.x 版本的语法是正确的，而且我已经尝试过你提供的两条命令，项目代码被正确地生成在了上述两个目录中

**Comment by Albert-cord** [comment]
#27 已经提PR修复该问题
