### ISSUE TITLE
TODO: throw errors properly

### ISSUE THREAD

**Issue by Albert-cord** [dolliejs/dollie#28]
https://github.com/dolliejs/dollie/blob/4f41e14a70ec30aaa8d7d63b64beb4dd45a28c6d/packages/%40dollie/cli/src/commands/init.ts#L314
代码里有几处错误没有处理，不管是通过onMessage给调用者处理还是直接throw都好  
不然使用者还得直接啃代码才知道哪里有问题  
或者这里是有其他考虑？

**Comment by lenconda** [comment]
In our branch `next`, there are more precise error handlers and information to help you find out what's going wrong. These will be fixed in the next version `4.0.0`.

<hr />

在我们的分支 `next` 中，错误处理和信息将会更精确，以帮助你找到问题出在哪里。上述内容将会在下一个版本 `4.0.0` 中被修复。
